### Snowbound Ambush

A shrill cry pierces the air, followed by guttural snarls from the snowdrifts nearby. Emerging from the swirling snow come a pack of [Frostbound Kobolds](#frostbound-kobold), their scaled bodies camouflaged against the white landscape.  There seem to be three to the north and two to the east.

The Kobolds, their eyes glinting with malicious intent, brandish makeshift spears and icy daggers. They dart in and out of cover, using the snowbanks and rocks for cover as they launch their ambush.

The treacherous terrain is uneven, with hidden icy patches that make movement perilous. The Kobolds use this to their advantage, trying to lure your party into these hazardous areas to gain the upper hand.

:::{.callout-note}
**DM**: The battle happens here.  There is little chance of the party convincing these monsters not to attack.
:::

After the ambush, there is a quiet calm as the remaining members of the wagon party come out from their wagons.  The sky begins to darken: it is almost night.
