### Returning to the Village

Emerging from the cavern's depths, the wagon party begins the long journey back. The travelers, now joined by the party, quickly bundle up in their winter gear, preparing for the continued trek through the unforgiving terrain.

The caravan sets off, the creaking of the wagons and the steady rhythm of horse hooves on the snow-covered ground marking their progression. The landscape, though still desolate, seems slightly less foreboding.

After a long but mercifully uneventful trek, in the distance the party sees the flickering lights of the village begin to emerge, casting a warm and inviting glow against the snowy backdrop.

You meet the Duke at the pub.  He is impressed with your work.  He rewards you with a sack of gold and a single basic weapon, as well as an invitation to dine with him the following night.

"Since you made it back alive, you've proven to me that you can brave the ice and snow.  I'll speak to you at dinner tomorrow regarding a new contract.  You should be well-equip to handle this one... though, it is of a more sensitive nature than retrieving the relic..."

Perhaps he is referring to the number of children over the past few months that have either gone missing or have been found exsanguinated.  Perhaps not.  The party will find out next time.